id = "sonder-theme"
name = "Sonder"
schema_version = 1
version = "0.1.0"
authors = ["José Duarte <duarte.gmj@gmail.com>"]
description = "A dark theme focused on the essentials"
repository = "https://github.com/jmg-duarte/sonder-zed"
